# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

  

target 'SDKForms' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SDKCore', :path=> '../SDKCore'

  target 'SDKFormsTests' do
   pod 'SwiftyMocky', :git => 'https://github.com/AppPear/SwiftyMocky', :tag => '4.2.0'
  end

end
