name: UnitTests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Testing SDK app
    runs-on: macos-11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Testing CardKitCore
        run: exec ./.github/scripts/test-card-kit-core.sh
      - name: Install Dependencies
        run: pod install
        shell: bash
      - name: Testing CardKit
        run: exec ./.github/scripts/test-card-kit.sh
      - name: Testing SampleApp
        run: exec ./.github/scripts/test-sample-app-ui.sh
